export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const ERROR_MESSAGE_RESET = 'ERROR_MESSAGE_RESET';

export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const SUCCESS_MESSAGE_RESET = 'SUCCESS_MESSAGE_RESET';
