export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';
export const POST_LIST_RESET = 'POST_LIST_RESET';

export const POST_ONE_REQUEST = 'POST_ONE_REQUEST';
export const POST_ONE_SUCCESS = 'POST_ONE_SUCCESS';
export const POST_ONE_FAIL = 'POST_ONE_FAIL';
export const POST_ONE_RESET = 'POST_ONE_RESET';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';
export const CREATE_POST_RESET = 'CREATE_POST_RESET';

export const ADD_LIKE_REQUEST = 'ADD_LIKE_REQUEST';
export const ADD_LIKE_SUCCESS = 'ADD_LIKE_SUCCESS';
export const ADD_LIKE_FAIL = 'ADD_LIKE_FAIL';
export const ADD_LIKE_RESET = 'ADD_LIKE_RESET';

export const ADD_LIKE_COMMENT_REQUEST = 'ADD_LIKE_COMMENT_REQUEST';
export const ADD_LIKE_COMMENT_SUCCESS = 'ADD_LIKE_COMMENT_SUCCESS';
export const ADD_LIKE_COMMENT_FAIL = 'ADD_LIKE_COMMENT_FAIL';
export const ADD_LIKE_COMMENT_RESET = 'ADD_LIKE_COMMENT_RESET';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const ADD_COMMENT_RESET = 'ADD_COMMENT_RESET';

export const ADD_IMAGE_REQUEST = 'ADD_IMAGE_REQUEST';
export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const ADD_IMAGE_FAIL = 'ADD_IMAGE_FAIL';
export const ADD_IMAGE_RESET = 'ADD_IMAGE_RESET';

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';
export const EDIT_POST_RESET = 'EDIT_POST_RESET';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_FAIL = 'EDIT_COMMENT_FAIL';

export const REPORT_COMMENT_REQUEST = 'REPORT_COMMENT_REQUEST';
export const REPORT_COMMENT_SUCCESS = 'REPORT_COMMENT_SUCCESS';
export const REPORT_COMMENT_FAIL = 'REPORT_COMMENT_FAIL';
