export const TENIS_LIST_REQUEST = 'TENIS_LIST_REQUEST';
export const TENIS_LIST_SUCCESS = 'TENIS_LIST_SUCCESS';
export const TENIS_LIST_FAIL = 'TENIS_LIST_FAIL';
export const TENIS_LIST_RESET = 'TENIS_LIST_RESET';
