export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const GETPROFILE_INFO_REQUEST = 'GETPROFILE_INFO_REQUEST';
export const GETPROFILE_INFO_SUCCESS = 'GETPROFILE_INFO_SUCCESS';
export const GETPROFILE_INFO_FAIL = 'GETPROFILE_INFO_FAIL';
export const GETPROFILE_INFO_RESET = 'GETPROFILE_INFO_RESET';

export const PROFILE_INFO_REQUEST = 'PROFILE_INFO_REQUEST';
export const PROFILE_INFO_SUCCESS = 'PROFILE_INFO_SUCCESS';
export const PROFILE_INFO_FAIL = 'PROFILE_INFO_FAIL';
export const PROFILE_INFO_RESET = 'PROFILE_INFO_RESET';

export const PROFILE_PASSWORD_REQUEST = 'PROFILE_PASSWORD_REQUEST';
export const PROFILE_PASSWORD_SUCCESS = 'PROFILE_PASSWORD_SUCCESS';
export const PROFILE_PASSWORD_FAIL = 'PROFILE_PASSWORD_FAIL';

export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAIL = 'PROFILE_DELETE_FAIL';

export const CONTACT_SEND_REQUEST = 'CONTACT_SEND_REQUEST';
export const CONTACT_SEND_SUCCESS = 'CONTACT_SEND_SUCCESS';
export const CONTACT_SEND_FAIL = 'CONTACT_SEND_FAIL';

export const ADD_FAVORITE_REQUEST = 'ADD_FAVORITE_REQUEST';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_FAIL = 'ADD_FAVORITE_FAIL';

export const DELETE_FAVORITE_REQUEST = 'DELETE_FAVORITE_REQUEST';
export const DELETE_FAVORITE_SUCCESS = 'DELETE_FAVORITE_SUCCESS';
export const DELETE_FAVORITE_FAIL = 'DELETE_FAVORITE_FAIL';
